# Generated by Django 5.1.6 on 2025-04-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default_avatar.jpg",
                help_text="Загрузите свой аватар",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
