# Generated by Django 5.1.6 on 2025-03-18 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0002_message_alter_newsletterrecipient_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название рассылки")),
                (
                    "start_sending",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время начала рассылки"
                    ),
                ),
                (
                    "finish_sending",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите дату и время окончания рассылки",
                        null=True,
                        verbose_name="Дата и время окончания рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Рассылка создана"),
                            ("launched", "Рассылка запущена"),
                            ("completed", "Рассылка завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "client",
                    models.ManyToManyField(
                        related_name="newsletters",
                        to="newsletters.newsletterrecipient",
                        verbose_name="Получатели рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletters",
                        to="newsletters.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
    ]
