# Generated by Django 5.1.6 on 2025-03-25 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Письмо", "verbose_name_plural": "Письма"},
        ),
        migrations.RenameField(
            model_name="newsletter",
            old_name="client",
            new_name="clients",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="finish_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="newsletters.message",
                verbose_name="Письмо",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_sending",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name="Дата и время начала рассылки"
            ),
        ),
    ]
