# Generated by Django 5.1.6 on 2025-04-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0005_message_owner_newsletter_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("created", "СОЗДАНА"), ("launched", "ЗАПУЩЕНА"), ("completed", "ЗАВЕРШЕНА")],
                default="created",
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterAttempting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time", models.DateTimeField(verbose_name="Дата и время попытки рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "УСПЕШНО"), ("failed", "НЕ УСПЕШНО")],
                        max_length=20,
                        verbose_name="Статус попытки рассылки",
                    ),
                ),
                ("server_answer", models.TextField()),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter",
                        to="newsletters.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
