# Generated by Django 5.1.6 on 2025-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0006_alter_newsletter_status_newsletterattempting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterattempting",
            name="date_time",
        ),
        migrations.AddField(
            model_name="newsletterattempting",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата и время попытки рассылки"),
        ),
    ]
