# Generated by Django 5.1.6 on 2025-04-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0007_remove_newsletterattempting_date_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletterattempting",
            old_name="server_answer",
            new_name="server_response",
        ),
    ]
