# Generated by Django 5.1.6 on 2025-04-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0008_rename_server_answer_newsletterattempting_server_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterattempting",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="newsletters.newsletter",
                verbose_name="Рассылка",
            ),
        ),
    ]
