# Generated by Django 5.1.6 on 2025-04-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0009_alter_newsletterattempting_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_newsletter_message", "Can view newsletter message")],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_view_newsletter", "Can view newsletter"),
                    ("can_change_status", "Can change status to completed"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletterattempting",
            options={"verbose_name": "Попытка рассылки", "verbose_name_plural": "Попытки рассылки"},
        ),
        migrations.AlterModelOptions(
            name="newsletterrecipient",
            options={
                "permissions": [("can_view_newsletter_recipient", "Can view newsletter recipient")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
